name: DockerHub Description

on:
  push:
    branches:
      - 'trunk'
    paths:
      - "*/*/README.md"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: "zabbix"
      SUBDIR: "alpine"
    strategy:
      fail-fast: false
      matrix:
        build:
          - agent
          - agent2
          - java-gateway                                                                       
          - proxy-mysql                                                                        
          - proxy-sqlite3                                                                      
          - server-mysql                                                                       
          - server-pgsql                                                                       
          - snmptraps                                                                          
          - web-apache-mysql                                                                   
          - web-apache-pgsql                                                                   
          - web-nginx-mysql
          - web-nginx-pgsql
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Update DockerHub repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}/zabbix-${{ matrix.build }}
          readme-filepath: ./${{ matrix.build }}/${{ env.SUBDIR }}/README.md
